### PR TITLE
Use smaller and compressed varients of buttons and form components

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description
Replace instances of `EuiButton` that don't have an explicit sizing attribute to `EuiSmallButton*`.
Replace instances of `Eui<form elements>` that don't have density attributes to `EuiCompressed<form elements>`.
Add and use `compressed` to DateRangePicker and FrequencyPicker.
 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by AWSHurneyt** [comment]
@AMoo-Miki We have issue https://github.com/opensearch-project/alerting-dashboards-plugin/issues/415 to track known flaky cypress tests. Looks like the tests failing in this PR are not mentioned in that issue. I'm wondering whether the changes caused some kind of regression, or whether the tests just need to be refactored to reflect the changes.

Do they pass locally for you?

**Comment by AMoo-Miki** [comment]
> @AMoo-Miki We have issue #415 to track known flaky cypress tests. Looks like the tests failing in this PR are not mentioned in that issue. I'm wondering whether the changes caused some kind of regression, or whether the tests just need to be refactored to reflect the changes.
> 
> Do they pass locally for you?

In one of the cases, the test starts populating the index pattern but is interrupted by the cluster being added to the page and then the index pattern is left blank.

Query-Level Monitors
       can have triggers
         with names that contain periods

https://github.com/user-attachments/assets/a6887c80-b275-4750-93f7-5ba7b90c7777

**Comment by AMoo-Miki** [comment]
Apparently, these have been failing for some time now: https://github.com/opensearch-project/alerting-dashboards-plugin/actions/workflows/cypress-workflow.yml

**Comment by AWSHurneyt** [comment]
The composite monitor spec does have a flaky test, but it looks like it passed in this PR from a few days ago. Which was the most recent merge to `main` before today.
https://github.com/opensearch-project/alerting-dashboards-plugin/pull/1004/checks

I'm rerunning the checks in PR 1010 now to see if maybe the tests are flaky.

**Comment by AMoo-Miki** [comment]
@AWSHurneyt The same 3 failed in https://github.com/opensearch-project/alerting-dashboards-plugin/actions/runs/10050410663/job/27778265636 which has no changes.

**Review by AWSHurneyt — APPROVED** [review]

**Review by riysaxen-amzn — APPROVED** [review]

**Comment by AWSHurneyt** [comment]
Auto backport to 2.16 failed. Will try to auto backport the 2.x PR (https://github.com/opensearch-project/alerting-dashboards-plugin/pull/1017).

**Pull request merged**
