### PR TITLE
[Look&Feel] apply missing pattern guidance to Alerting experience

### PR DESCRIPTION
**Pull request by zhongnansu**
### Description
Apply missing pattern guidance to Alerting experience

image

 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by virajsanghvi — APPROVED** [review]
Approving assuming failed check is not related

**Comment by zhongnansu** [comment]
> Approving assuming failed check is not related

CI passed now

**Comment by zhongnansu** [comment]
@rishabhmaurya  @AWSHurneyt  Could you help approve and backport the PR, thanks

**Comment by AWSHurneyt** [comment]
@zhongnansu added 2.x backport label. Any other backports needed for this PR?

**Review by AWSHurneyt — APPROVED** [review]

**Review by riysaxen-amzn — APPROVED** [review]

**Comment by AWSHurneyt** [comment]
@zhongnansu 
The auto backport failed. Could you raise a PR to backport the changes?

**Comment by zhongnansu** [comment]
@AWSHurneyt Only backport to 2.x is needed, thanks. I'll manually backport it, thanks

**Comment by zhongnansu** [comment]
@AWSHurneyt auto backport succeeded after other backport PRs are in https://github.com/opensearch-project/alerting-dashboards-plugin/pull/1008 cc: @riysaxen-amzn

**Pull request merged**
