### PR TITLE
Fixed a bug impacting data filter configuration through the visual editor.

### PR DESCRIPTION
**Pull request by AWSHurneyt**
### Description
1. Fixed a bug impacting data filter configuration through the visual editor.
2. Added integration test.
3. Reduced cypress test flakiness.
 
### Issues Resolved
1. Bug issue https://github.com/opensearch-project/alerting-dashboards-plugin/issues/558
2. Flaky test tracking issue https://github.com/opensearch-project/alerting-dashboards-plugin/issues/415
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by AWSHurneyt** [comment]
Created a separate PR to resolve the unit test failure, as it seems unrelated to these changes.
https://github.com/opensearch-project/alerting-dashboards-plugin/pull/576

**Comment by AWSHurneyt** [comment]
> Created a separate PR to resolve the unit test failure, as it seems unrelated to these changes. #576

That PR was merged. Pulled those changes into the dev branch for this PR, and now the unit tests are passing.

**Comment by AWSHurneyt** [comment]
The cypress tests are expected to fail on `main` branch at the moment.

**Review by lezzago — APPROVED** [review]

**Review by getsaurabh02 — COMMENTED** [review]
LGTM

**Review by getsaurabh02 — APPROVED** [review]

**Comment by AWSHurneyt** [comment]
Hi @zakisaad ,
We don't have a scheduled date for 2.7 patch at the moment. This fix is present in OpenSearch 2.9.
https://opensearch.org/releases.html

As a workaround, data filters can be configured using the `extraction query editor` UI. Here's an example of what it would look like if you wanted to add `products.product_id is 123` and `user is steph` filters to the `opensearch_dashboards_sample_data_ecommerce` index.
```
{
  "size": 0,
  "aggregations": {
    "composite_agg": {
      "composite": {
        "sources": [
          {
            "user": {
              "terms": {
                "field": "user"
              }
            }
          }
        ]
      },
      "aggs": {}
    }
  },
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "order_date": {
              "gte": "{{period_end}}||-1h",
              "lte": "{{period_end}}",
              "format": "epoch_millis"
            }
          }
        },
        {
          "term": {
            "products.product_id": 123
          }
        },
        {
          "term": {
            "user": "steph"
          }
        }
      ]
    }
  }
}
```

**Pull request merged**
